# Generated by Django 4.2 on 2023-04-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
